### PR TITLE
Channel Logo Upload

### PR DESCRIPTION
**Pull request by rafaelvieiras**
### Explanation of the changes, problem that they are intended to fix.

This is Just an upload for logo of channels.

image

And I fixed images links for docker hub
image

...

### All Submissions:

* [x] I have read the code of conduct.
* [x] I am submitting to the correct base branch

### New features

* [x] I understand that the feature may not be accepted if it doesn't fit the upstream app's planned design direction. But that in this case I am encouraged to share this as an available modification other users can use if they want.

### CODE REVIEW

**Comment by nwithan8** [comment]
Following for potential API update for Python library

**Comment by vexorian** [comment]
Cool.

I'll tweak it later or maybe you can do it too. Would be nice if the dialog filtered only image files. Some sort of message to notify you that the file was uploaded would be nice to have as well. It's already better UX than what we had so I merged it without needing those changes.

**Comment by vexorian** [comment]
> Following for potential API update for Python library

New modification and the api endpoint is different, works for any image upload and not just channel logo.

**Comment by vexorian** [comment]
It is actually quite risky to have this sort of thing in a completely open door that is dizqueTV. But there are already many things a hacker could do if they find access to dizqueTV's port. Hence why it's never recommended to put it on a publically accessible port.

**Comment by nwithan8** [comment]
Looking over your recent commit, how does the server know what channel to associate this uploaded image with? I'm not seeing a channel number/id as any kind of parameter

**Pull request merged**
